auto-collect/collect: Fix TPMSpy theoretically creating packets-$N.bin for N not 01
This should never happen with auto-collect, but TPMSpy is able to handle
multiple connections to the same swtpm instance at once, resulting in
multiple packet captures.

diff --git a/auto-collect/collect b/auto-collect/collect
--- a/auto-collect/collect
+++ b/auto-collect/collect
@@ -105,7 +105,13 @@ for trace_no in $(seq -w 0 "$((count - 1))"); do
 
 	cp "$tpmspy_dir"/tpmspy.log tpmspy.log
 	cp "$tpmspy_dir"/swtpm.log swtpm.log
-	cp "$tpmspy_dir"/packets.bin tpmspy.bin
+
+	if [ $(ls "$tpmspy_dir"/packets-*.bin | wc -l) -ne 1 ]; then
+		echo "collect: Unique packets-01.bin not found, copying all to be sure" >&2
+		cp "$tpmspy_dir"/packets-*.bin .
+	else
+		cp "$tpmspy_dir"/packets-*.bin tpmspy.bin
+	fi
 
 	cd "$_pwd" || die "cd $_pwd"
 	unset _pwd
